### ISSUE TITLE
Login Button Issue(UserLogin)

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#71]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/3dfdcca9-c38f-497a-992a-475e4da0a2d3)
Even if the email and password fields were empty, the login button was being clicked in user login page
instead, it should show some message to user of the fields being empty.

**Comment by pranishbrah** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/6bcaeea9-c519-4757-bbbe-1387853899de)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/ba58717c-fa2c-4539-8adc-abd23662b085)
Alert message is added so that if the fields are empty and user clicks login button, it shows the message.

**Comment by Manash111** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/6bcaeea9-c519-4757-bbbe-1387853899de)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/ba58717c-fa2c-4539-8adc-abd23662b085)
Alert message is added so that if the fields are empty and user clicks login button, it shows the message.
